Repository KKKK-Stempo/stempo-android, pull requests merged in 2024-08, with the labels that each got.

#37 [Feat/#36] Main / connect record api
  app/src/main/java/com/kkkk/stempo/di/AuthInterceptor.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
Labels: FEAT ✨, 동민 🎅🏻

#39 [FIX/#38] 리듬뷰 / 화면 꺼짐 방지 추가
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyFragment.kt
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/layout/item_study_exercise.xml
  presentation/src/main/res/layout/item_study_information.xml
Labels: FIX 🔨, 상호 🍀

#41 [FEAT/#40] 워치앱 모듈 설정
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  stempo/build.gradle.kts
  stempo/lint.xml
  stempo/src/main/AndroidManifest.xml
  stempo/src/main/java/com/kkkk/stempo/presentation/WatchActivity.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/theme/Theme.kt
  stempo/src/main/res/drawable/splash_icon.xml
  stempo/src/main/res/mipmap-hdpi/ic_launcher.webp
  stempo/src/main/res/mipmap-mdpi/ic_launcher.webp
  stempo/src/main/res/mipmap-xhdpi/ic_launcher.webp
  stempo/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  stempo/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  stempo/src/main/res/values-round/strings.xml
  stempo/src/main/res/values/strings.xml
  stempo/src/main/res/values/styles.xml
Labels: FEAT ✨, 상호 🍀

#44 [Feat/#42] watch os UI
  gradle/libs.versions.toml
  stempo/build.gradle.kts
  stempo/src/main/AndroidManifest.xml
  stempo/src/main/java/com/kkkk/stempo/presentation/WatchActivity.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/home/HomeScreen.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/home/HomeSideEffect.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/home/HomeState.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/home/HomeViewModel.kt
  stempo/src/main/res/drawable/ic_play.xml
  stempo/src/main/res/drawable/ic_stop.xml
  stempo/src/main/res/drawable/img_rhythm_bg_purple.xml
Labels: FEAT ✨, UI 💐, 동민 🎅🏻

#50 [FEAT/#46] Data Layer API로 워치 & 폰 데이터 항목 동기화
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core-di/build.gradle.kts
  core-di/src/main/java/com/kkkk/di/ManagerModule.kt
  core-ui/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/manager/WearableDataManager.kt
  stempo/build.gradle.kts
  stempo/src/main/AndroidManifest.xml
  stempo/src/main/java/com/kkkk/stempo/presentation/MyApp.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/WatchActivity.kt
Labels: FEAT ✨, 상호 🍀

#52 [FEAT/#51] 워치 걸음 측정 폰으로 전송 구현
  core-di/src/main/java/com/kkkk/di/ManagerModule.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/manager/PhoneDataManager.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/WatchActivity.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/home/HomeViewModel.kt
  stempo/src/main/java/com/kkkk/stempo/presentation/manager/WearableDataManger.kt
Labels: FEAT ✨, 상호 🍀
