Repository KKKK-Stempo/stempo-android, pull requests merged in 2024-07, with the labels that each got.

#4 [ADD/#3] 프로젝트 초기 세팅
  presentation/src/main/res/values/strings.xml
Labels: ADD ➕, 상호 🍀

#6 [ADD/#5] 메인뷰 / 바텀 네비게이션 설정
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/kkkk/presentation/main/MainActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/report/ReportFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyFragment.kt
  presentation/src/main/res/drawable/ic_my_selected.xml
  presentation/src/main/res/drawable/ic_my_unselected.xml
  presentation/src/main/res/drawable/ic_report_selected.xml
  presentation/src/main/res/drawable/ic_report_unselected.xml
  presentation/src/main/res/drawable/ic_rhythm_selected.xml
  presentation/src/main/res/drawable/ic_rhythm_unselected.xml
  presentation/src/main/res/drawable/ic_study_selected.xml
  presentation/src/main/res/drawable/ic_study_unselected.xml
  presentation/src/main/res/drawable/sel_bnv_my.xml
  presentation/src/main/res/drawable/sel_bnv_report.xml
  presentation/src/main/res/drawable/sel_bnv_rhythm.xml
  presentation/src/main/res/drawable/sel_bnv_study.xml
  presentation/src/main/res/drawable/sel_bnv_text_color.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_report.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/menu/menu_main.xml
  presentation/src/main/res/values/strings.xml
Labels: ADD ➕, 상호 🍀

#8 [UI/#7] 리듬뷰 / UI 구현
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/res/drawable/ic_change.xml
  presentation/src/main/res/drawable/shape_dark_fill_12_rect.xml
  presentation/src/main/res/drawable/shape_gray200_fill_circle.xml
  presentation/src/main/res/drawable/shape_gray500_fill_100_rect.xml
  presentation/src/main/res/drawable/shape_green50_line_17_rect.xml
  presentation/src/main/res/drawable/shape_purple10_fill_12_rect.xml
  presentation/src/main/res/drawable/shape_purple50_fill_circle.xml
  presentation/src/main/res/drawable/shape_purple50_line_17_rect.xml
  presentation/src/main/res/drawable/shape_sky50_line_17_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_top20_rect.xml
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_report.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/styles.xml
  presentation/src/main/res/values/themes.xml
Labels: UI 💐, 상호 🍀

#11 [UI/#10] splash
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/kkkk/core/extension/ActivityExt.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/splash/SplashViewModel.kt
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/values/themes.xml
Labels: FEAT ✨, 동민 🎅🏻

#13 [UI/#12] onboarding
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/kkkk/core/extension/ActivityExt.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingEndFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingMeasureFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingStartFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingState.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/splash/SplashActivity.kt
  presentation/src/main/res/drawable/ic_logo_full_name.xml
  presentation/src/main/res/drawable/ic_logo_illustration.xml
  presentation/src/main/res/drawable/ic_logo_illustration_end.xml
  presentation/src/main/res/drawable/ic_progrssbar_full.xml
  presentation/src/main/res/layout/activity_onboarding.xml
  presentation/src/main/res/layout/fragment_onboarding_end.xml
  presentation/src/main/res/layout/fragment_onboarding_measure.xml
  presentation/src/main/res/layout/fragment_onboarding_start.xml
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, 동민 🎅🏻

#15 [UI/#9] 기록뷰 / UI 구현 및 MpChart 활용한 그래프 구현
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/report/ReportFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/report/ReportViewModel.kt
  presentation/src/main/res/drawable/ic_drop_down.xml
  presentation/src/main/res/drawable/ic_drop_up.xml
  presentation/src/main/res/drawable/ic_next_purple.xml
  presentation/src/main/res/drawable/shape_gray100_fill_8_rect.xml
  presentation/src/main/res/drawable/shape_gray300_dash_line.xml
  presentation/src/main/res/layout/fragment_report.xml
  presentation/src/main/res/values/strings.xml
Labels: UI 💐, 상호 🍀

#16 [UI/#14] study
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyExerciseFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyInformationFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyViewPagerAdapter.kt
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_arrow_right.xml
  presentation/src/main/res/drawable/img_default_content.xml
  presentation/src/main/res/drawable/shape_gray200_line_8_rect.xml
  presentation/src/main/res/drawable/shape_purple50_fill_12_rect.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/layout/fragment_study_exercise.xml
  presentation/src/main/res/layout/fragment_study_information.xml
  presentation/src/main/res/layout/item_study_exercise.xml
  presentation/src/main/res/layout/item_study_information.xml
  presentation/src/main/res/values/strings.xml
Labels: UI 💐, 동민 🎅🏻

#19 [FEAT/#18] 기록뷰 / 그래프 API 구현
  app/src/main/java/com/kkkk/stempo/di/DataSourceModule.kt
  app/src/main/java/com/kkkk/stempo/di/RepositoryModule.kt
  app/src/main/java/com/kkkk/stempo/di/ServiceModule.kt
  data/src/main/java/com/kkkk/data/dataSource/RecordDataSource.kt
  data/src/main/java/com/kkkk/data/dataSource/RhythmDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RecordDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RhythmDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/BaseResponse.kt
  data/src/main/java/com/kkkk/data/dto/response/RecordDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RecordRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RhythmRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RecordService.kt
  data/src/main/java/com/kkkk/data/service/RhythmService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/response/RecordModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RecordRepository.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RhythmRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/report/ReportViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/res/drawable/img_record_empty.xml
  presentation/src/main/res/drawable/img_rhythm_purple.xml
  presentation/src/main/res/drawable/mock_rhythm_stop.png
  presentation/src/main/res/layout/fragment_record.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
Labels: FEAT ✨, 상호 🍀

#22 [Feature/#17] onboarding sensor
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingEndFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingEndFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingMeasureFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingStartFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingState.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashViewModel.kt
  presentation/src/main/res/layout/fragment_onboarding_end.xml
  presentation/src/main/res/layout/fragment_onboarding_measure.xml
  presentation/src/main/res/raw/stempo_progressbar.json
  presentation/src/main/res/raw/stempo_walk.json
Labels: FEAT ✨, 동민 🎅🏻

#24 [Feat/#23] sign in
  app/src/main/java/com/kkkk/stempo/di/AuthInterceptor.kt
  data/src/main/java/com/kkkk/data/dataSource/AuthDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/response/AuthTokenDto.kt
  data/src/main/java/com/kkkk/data/local/UserSharedPref.kt
  data/src/main/java/com/kkkk/data/local/UserSharedPrefImpl.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/UserRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/AuthService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/response/AuthTokenModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/AuthRepository.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/UserRepository.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashViewModel.kt
Labels: FEAT ✨, 동민 🎅🏻

#32 [FEAT/#30] 리듬뷰 / 리듬 측정 결과 저장 API 구현
  data/src/main/java/com/kkkk/data/dataSource/RhythmDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RhythmDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/RecordRequestDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RhythmRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RhythmService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RecordRequestModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RhythmRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmSaveDialog.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/res/drawable/shape_white_fill_16_rect.xml
  presentation/src/main/res/layout/dialog_rhythm_save.xml
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, 상호 🍀

#29 [FEAT/#28] 리듬뷰 / 단계별 이미지 에셋 설정 및 재생속도 조정
  data/src/main/java/com/kkkk/data/dataSource/RhythmDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RhythmDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/RecordRequestDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RhythmRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RhythmService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RecordRequestModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RhythmRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmSaveDialog.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/res/drawable/ic_play.xml
  presentation/src/main/res/drawable/ic_stop.xml
  presentation/src/main/res/drawable/img_rhythm_bg_green.xml
  presentation/src/main/res/drawable/img_rhythm_bg_purple.xml
  presentation/src/main/res/drawable/img_rhythm_bg_sky.xml
  presentation/src/main/res/drawable/mock_rhythm_stop.png
  presentation/src/main/res/drawable/shape_white_fill_16_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_green50_line_17_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_purple50_line_17_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_sky50_line_17_rect.xml
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/layout/dialog_rhythm_save.xml
  presentation/src/main/res/layout/fragment_record.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
  presentation/src/main/res/raw/stempo_loading.json
  presentation/src/main/res/raw/stempo_rhythm_green.json
  presentation/src/main/res/raw/stempo_rhythm_purple.json
  presentation/src/main/res/raw/stempo_rhythm_sky.json
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, 상호 🍀

#33 [Feat/#27] study api 1차 연결
  app/src/main/java/com/kkkk/stempo/di/DataSourceModule.kt
  app/src/main/java/com/kkkk/stempo/di/RepositoryModule.kt
  app/src/main/java/com/kkkk/stempo/di/ServiceModule.kt
  data/src/main/java/com/kkkk/data/dataSource/StudyDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/StudyDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/response/StudyDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/StudyRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/StudyService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/response/StudyModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/StudyRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyExerciseFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyInformationFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyViewModel.kt
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/layout/fragment_study_exercise.xml
  presentation/src/main/res/layout/fragment_study_information.xml
Labels: FEAT ✨, 동민 🎅🏻
