Repository KKKK-Stempo/stempo-android, pull requests merged in 2024-10, with the labels that each got.

#77 [FIX/#74] 복지관 QA 대응
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/StretchFragment.kt
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/raw/music_bpm_100.mp3
  presentation/src/main/res/raw/music_bpm_110.mp3
  presentation/src/main/res/raw/music_bpm_120.mp3
  presentation/src/main/res/raw/music_bpm_60.mp3
  presentation/src/main/res/raw/music_bpm_70.mp3
  presentation/src/main/res/raw/music_bpm_80.mp3
  presentation/src/main/res/raw/music_bpm_90.mp3
  presentation/src/main/res/raw/music_stretch.mp3
  presentation/src/main/res/raw/rhythm_stretch.mp3
  presentation/src/main/res/values/strings.xml
  watch/src/main/java/com/kkkk/stempo/presentation/WatchActivity.kt
Labels: FIX 🔨, 상호 🍀

#79 [Feat/#76] statistics 구현
  data/src/main/java/com/kkkk/data/dataSource/RecordDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RecordDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/response/StatisticsDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RecordRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RecordService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/response/StatisticsModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RecordRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/res/drawable/ic_badge_sequence.xml
  presentation/src/main/res/drawable/ic_badge_today.xml
  presentation/src/main/res/drawable/ic_badge_week.xml
  presentation/src/main/res/layout/fragment_record.xml
  presentation/src/main/res/values/strings.xml
  watch/src/main/java/com/kkkk/stempo/presentation/home/HomeViewModel.kt
Labels: FEAT ✨, 동민 🎅🏻

#81 [Docs #80] update readme
  README.md
Labels: UI 💐, 동민 🎅🏻
