Repository KKKK-Stempo/stempo-android, pull requests merged in 2024-09, with the labels that each got.

#56 [Feat/#55] fix step sensor and onboarding
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingMeasureFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingStartFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/res/layout/dialog_single_button.xml
  presentation/src/main/res/layout/fragment_onboarding_measure.xml
  presentation/src/main/res/layout/fragment_onboarding_start.xml
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, FIX 🔨, 동민 🎅🏻

#59 [Feat/#58] auth
  data/src/main/java/com/kkkk/data/dataSource/AuthDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/AuthDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/AuthRequestDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/AuthRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/AuthService.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/AuthRepository.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashViewModel.kt
Labels: FIX 🔨, HOTFIX 🚑️, 동민 🎅🏻

#62 [Feat/#57] homework UI / API
  data/src/main/java/com/kkkk/data/dataSource/StudyDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/StudyDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/HomeworkDescriptionDto.kt
  data/src/main/java/com/kkkk/data/dto/request/HomeworkDto.kt
  data/src/main/java/com/kkkk/data/dto/response/StudyDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/StudyRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/StudyService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/response/StudyModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/StudyRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyAdapter.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyExerciseFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyInformationFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyViewHolder.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/study/StudyViewPagerAdapter.kt
  presentation/src/main/res/drawable/cursor_drawable.xml
  presentation/src/main/res/drawable/ic_cancel.xml
  presentation/src/main/res/drawable/ic_checkbox_checked.xml
  presentation/src/main/res/drawable/ic_checkbox_unchecked.xml
  presentation/src/main/res/drawable/img_study_empty.xml
  presentation/src/main/res/drawable/layer_list_progressbar.xml
  presentation/src/main/res/drawable/shape_seekbar_thumb.xml
  presentation/src/main/res/drawable/shape_toggle_background.xml
  presentation/src/main/res/drawable/shape_toggle_selected.xml
  presentation/src/main/res/layout/dialog_add_homework.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/layout/fragment_study_exercise.xml
  presentation/src/main/res/layout/fragment_study_information.xml
  presentation/src/main/res/layout/item_custom_toggle.xml
  presentation/src/main/res/layout/item_study_check_string.xml
  presentation/src/main/res/layout/item_study_exercise.xml
  presentation/src/main/res/layout/item_study_information.xml
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, UI 💐, 동민 🎅🏻

#65 [FIX/#64] 리듬뷰 / 서버 변동사항 대응
  data/src/main/java/com/kkkk/data/dataSource/RhythmDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RhythmDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/RhythmRequestDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RhythmRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RhythmService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RhythmRequestModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RhythmRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/StretchFragment.kt
  presentation/src/main/res/layout/fragment_record.xml
Labels: FIX 🔨, 상호 🍀

#63 [UI/#61] 리듬뷰 / UI 수정사항 대응
  data/src/main/java/com/kkkk/data/dataSource/RhythmDataSource.kt
  data/src/main/java/com/kkkk/data/dataSourceImpl/RhythmDataSourceImpl.kt
  data/src/main/java/com/kkkk/data/dto/request/RhythmRequestDto.kt
  data/src/main/java/com/kkkk/data/repositoryImpl/RhythmRepositoryImpl.kt
  data/src/main/java/com/kkkk/data/service/RhythmService.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RhythmRequestModel.kt
  domain/src/main/kotlin/com/kkkk/domain/repository/RhythmRepository.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainActivity.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/StretchFragment.kt
  presentation/src/main/res/drawable/shape_gray200_fill_17_rect.xml
  presentation/src/main/res/drawable/shape_gray200_fill_26_rect.xml
  presentation/src/main/res/drawable/shape_green50_fill_17_rect.xml
  presentation/src/main/res/drawable/shape_purple50_fill_17_rect.xml
  presentation/src/main/res/drawable/shape_sky50_fill_17_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_26_rect.xml
  presentation/src/main/res/drawable/shape_white_fill_gray600_line_17_rect.xml
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/layout/fragment_record.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
  presentation/src/main/res/layout/fragment_stretch.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/values/appearances.xml
  presentation/src/main/res/values/strings.xml
Labels: UI 💐, 상호 🍀

#68 [Feat/#66] fix sensor api error
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingMeasureFragment.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingViewModel.kt
Labels: FIX 🔨, 동민 🎅🏻

#69 [FEAT/#67] bpm별 음악 재생 추가 & 비트 비동기 연결
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/StretchFragment.kt
  presentation/src/main/res/raw/music_bpm_100.mp3
  presentation/src/main/res/raw/music_bpm_110.mp3
  presentation/src/main/res/raw/music_bpm_120.mp3
  presentation/src/main/res/raw/music_bpm_60.mp3
  presentation/src/main/res/raw/music_bpm_70.mp3
  presentation/src/main/res/raw/music_bpm_80.mp3
  presentation/src/main/res/raw/music_bpm_90.mp3
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, 상호 🍀
