Repository KKKK-Stempo/stempo-android, pull requests merged in 2025-01, with the labels that each got.

#85 [FEAT/#84] add compose dependencies
  .github/ISSUE_TEMPLATE/stempo-issue-template.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileScreen.kt
Labels: FEAT ✨, 동민 🎅🏻

#90 [Feat/#89] Typhographay를 설정합니다.
  presentation/src/main/java/com/kkkk/presentation/main/MainBottomBar.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainNavigation.kt
  presentation/src/main/java/com/kkkk/presentation/main/theme/Theme.kt
  presentation/src/main/java/com/kkkk/presentation/main/theme/Typography.kt
Labels: FEAT ✨, 동민 🎅🏻

#92 [UI/#91] 리듬뷰 / Compose Migration
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/MainScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmMode.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmState.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/ModifierExt.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBitItem.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBpmItem.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmChip.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmModeToggle.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmUpDownBtn.kt
  presentation/src/main/java/com/kkkk/presentation/main/theme/Theme.kt
  presentation/src/main/java/com/kkkk/presentation/main/theme/Typography.kt
  presentation/src/main/res/drawable/ic_drag_handle.xml
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/values/strings.xml
Labels: UI 💐, 상호 🍀

#96 [FIX/#95] 리듬뷰 / 기능 부분 로직 개선
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RecordRequestModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmState.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
Labels: FIX 🔨, 상호 🍀

#98 [UI/#97] 기록뷰 / Compose Migration
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordSideEffect.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordState.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/component/DottedShape.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/component/RecordLineChart.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBottomSheet.kt
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, UI 💐, 상호 🍀

#100 [UI/#99] 프로필뷰 / Compose Migration
  presentation/src/main/java/com/kkkk/presentation/main/component/ModifierExt.kt
  presentation/src/main/java/com/kkkk/presentation/main/component/OneButtonDialog.kt
  presentation/src/main/java/com/kkkk/presentation/main/component/TwoButtonDialog.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileSideEffect.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileState.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/model/ProfileButtonType.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmState.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBitItem.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBpmItem.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmModeToggle.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmUpDownBtn.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/model/PlayState.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/model/RhythmMode.kt
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, UI 💐, 상호 🍀

#102 [UI/#101] 과제뷰 / Compose Migration
  presentation/src/main/java/com/kkkk/presentation/main/MainBottomBar.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainNavigation.kt
  presentation/src/main/java/com/kkkk/presentation/main/MainScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/component/TextFieldDialog.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkSideEffect.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkState.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/component/HomeworkModeToggle.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/component/HomeworkProgressBarBox.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/component/HomeworkTaskList.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/model/HomeworkMode.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/navigation/HomeworkNavigation.kt
  presentation/src/main/java/com/kkkk/presentation/main/navigation/RouteModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/result/ResultScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/result/navigation/ResultNavigation.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: FEAT ✨, UI 💐, 상호 🍀

#104 [FIX/#103] 메인뷰 기존 XML뷰 제거
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/XmlMainActivity.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlprofile/XmlProfileFragment.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlprofile/XmlProfileViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlprofile/XmlProfileWithDrawDialog.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrecord/XmlRecordFragment.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrecord/XmlRecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlRhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlRhythmFragment.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlRhythmSaveDialog.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlRhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlStretchFragment.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlrhythm/XmlWatchSyncDialog.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlstudy/StudyAdapter.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlstudy/StudyFragment.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlstudy/StudyViewHolder.kt
  presentation/src/main/java/com/kkkk/presentation/xmlmain/xmlstudy/StudyViewModel.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/bottom_sheet_rhythm.xml
  presentation/src/main/res/layout/dialog_add_homework.xml
  presentation/src/main/res/layout/dialog_profile_with_draw.xml
  presentation/src/main/res/layout/dialog_rhythm_save.xml
  presentation/src/main/res/layout/dialog_watch_sync.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_record.xml
  presentation/src/main/res/layout/fragment_rhythm.xml
  presentation/src/main/res/layout/fragment_stretch.xml
  presentation/src/main/res/layout/fragment_study.xml
  presentation/src/main/res/layout/item_custom_toggle.xml
  presentation/src/main/res/layout/item_study_check_string.xml
  presentation/src/main/res/menu/menu_main.xml
Labels: FIX 🔨, 상호 🍀
