Repository KKKK-Stempo/stempo-android, pull requests merged in 2025-02, with the labels that each got.

#107 [FEAT/#106] records dto를 수정합니다
  data/src/main/java/com/kkkk/data/dto/request/RecordRequestDto.kt
  domain/src/main/kotlin/com/kkkk/domain/entity/request/RecordRequestModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
Labels: FIX 🔨, 동민 🎅🏻

#109 [FEAT/#108] Amplitude 설정 및 데이터 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kkkk/stempo/MyApp.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/homework/HomeworkViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/profile/ProfileViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/record/RecordViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/manager/AmplitudeManager.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/terms/TermsActivity.kt
Labels: FEAT ✨

#113 [HOTFIX/#112] 리듬뷰 바텀시트 스크롤 설정
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBitItem.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBottomSheet.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/component/RhythmBpmItem.kt
Labels: HOTFIX 🚑️

#115 [FEAT] MediaPlayer -> ExoPlayer 마이그레이션
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmScreen.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/manager/MusicManager.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
Labels: FEAT ✨

#119 [HOTFIX/#118] 스플래쉬 뷰 로그인 로직 수정
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/onbarding/OnboardingViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashActivity.kt
  presentation/src/main/java/com/kkkk/presentation/onboarding/splash/SplashViewModel.kt
Labels: HOTFIX 🚑️

#122 [FEAT/#120] Audio Focus 설정
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/RhythmViewModel.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/manager/AudioFocusCallback.kt
  presentation/src/main/java/com/kkkk/presentation/main/rhythm/manager/AudioFocusManager.kt
Labels: FEAT ✨
